package enums;

public enum buffType {

	//Generel types
	LOWROLL, HIGHROLL, STANDARTROLL, BLOCK, STRENGTH, AGILITY, INTELLIGENCE, BLEED, DAMAGE, MAX_HEALTH, MAX_MANA, MAX_ENERGY,
	
	//Lowroll-specifics
	MELEE_LOW, RANGED_LOW, MAGIC_LOW, BUFF_LOW, DEBUFF_LOW,
	
	//Highroll-specifics
	MELEE_HIGH, RANGED_HIGH, MAGIC_HIGH, BUFF_HIGH, DEBUFF_HIGH,
	
	//Block-specifics
	MELEE_BLOCK, RANGED_BLOCK, MAGIC_BLOCK,
	
	//Damage-specifics
	MELEE_DAMAGE, RANGED_DAMAGE, MAGIC_DAMAGE;
}
